---
title: '02.2'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r}
"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
serv.dir <- ""
work.dir.serv <- serv.dir %&% 
  "popgen/02.1_terastructure/mais_amr_afr_eur_mcps10k/"
tera.dir.pre <- "n11989-k3-l199247-select_rfreq_"
tera.dir.suf <- "-seed1"
```


```{r}
rfreq.vec <- c("05","10","15","20")
```

```{r}
build_validation_df <- function(rfreq.vec){
  out.df <- c()
  for (rfreq in rfreq.vec){
    df <- fread(work.dir.serv %&% "output_files/" %&% tera.dir.pre %&% 
                  rfreq %&% tera.dir.suf %&% "/validation.txt")
    iter <- 0:(dim(df)[1]-1)
    build.df <- data.frame("rfreq"=rfreq,"comp.iter"=iter,"iter.num"=df$V1,
                           "time.elapsed"=df$V2,"validation.likelihood"=df$V3,
                           "num.sampled.snps"=df$V4,"perplexity"=df$V5,
                           stringsAsFactors = F)
    out.df <- rbind(out.df,build.df)
  }
  return(out.df)
}
```

```{r}
val.df <- build_validation_df(rfreq.vec)
```

```{r}

plt1 <- ggplot(data=val.df,
              aes(x=comp.iter,y=validation.likelihood)) + 
  geom_line(aes(col=rfreq)) + 
  coord_cartesian(ylim=c(-0.6970,-0.6965)) + 
  theme_classic()

plt2 <- ggplot(data=val.df,
              aes(x=comp.iter,y=time.elapsed)) + 
  geom_line(aes(col=rfreq)) + 
  theme_classic()

```

```{r}
library(gridExtra)
plt <- grid.arrange(plt1,plt2,nrow=2)
ggsave(plot=plt,filename = work.dir.serv %&% "output_files/select-rfreq.png",
       height=4,width=6)
```


After reviewing the validation likelihood convergence trends, values, and time to convergence, it seems that the 
10% rfreq number is the best option as it plateaus with little oscillation, obtains the highest validation likelihood, 
and is considerably faster than 15% and 20% values.


