---
title: "04.2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}

"%&%" <- function(a,b) paste0(a,b)
library("data.table")
library("tidyverse")
library("bigsnpr")

serv.dir <- "./"
base.dir <- serv.dir %&% "popgen/01_pca/public_mais/"
work.dir <- base.dir %&% "04_mais_rsq90/mais_yri_ibs/"
file.dir <- work.dir %&% "bigsnpr_output/"
plink.dir <- base.dir %&% "merged_mais/"
plink.pre <- "merged_mais_rsq90"
bed.file <- plink.dir %&% plink.pre %&% ".bed"

```


```{r}
obj.svd <- readRDS(file.dir %&% "svd_unrelateds_maf01.rds")
prob <- bigutilsr::prob_dist(obj.svd$u, ncores = 1)
S <- prob$dist.self / sqrt(prob$dist.nn)
write_rds(x=S,file.dir %&% "knn-dist-stats_unrelateds_maf01.rds")
```

```{r}
hist.plt <- ggplot() +
  geom_histogram(aes(S), color = "#000000",
                 fill = "#000000", alpha = 0.5) +
  theme_bigstatsr() +
  labs(x = "Statistic of outlierness", y = "Frequency (sqrt-scale)")
ggsave(plot=hist.plt,filename=file.dir %&% "plots/svd_unrelateds_maf01_histogram.png",
       height=4,width=8)
```

From manual inspection, it doesn't seem that any outliers are clear 

```{r}
# PCs 1-12
setA0 <- plot_grid(plotlist = lapply(1:6, function(k) {
  plot(obj.svd, type = "scores", scores = 2 * k - 1:0, coeff =0.6) +
    aes(color = S) +
    scale_colour_viridis_c()
}), scale = 0.95)
ggsave(plot=setA0,filename=file.dir %&% 
  "plots/outlier-detection_unrelateds_maf01_pc1-12.png", width=8, height=5)

# PCs 14-20
setA <- plot_grid(plotlist = lapply(7:10, function(k) {
  plot(obj.svd, type = "scores", scores = 2 * k - 1:0, coeff =0.6) +
    aes(color = S) +
    scale_colour_viridis_c()
}), scale = 0.95)
ggsave(plot=setA,filename=file.dir %&% 
  "plots/outlier-detection_unrelateds_maf01_pc13-20.png", width=8, height=5)

```

Further inspection using a threshold of 0.9 (based on histogram)

```{r}
setB0 <- plot_grid(plotlist = lapply(1:6, function(k) {
  plot(obj.svd, type = "scores", scores = 2 * k - 1:0, coeff = 0.6) +
    aes(color = S > 0.9) +  # threshold based on histogram
    scale_colour_viridis_d()
}), scale = 0.95)
ggsave(plot=setB0,filename=file.dir %&% 
  "plots/outlier-detection_unrelateds_maf01_pc1-12_threshold-statp9.png", width=8, height=5)

setB <- plot_grid(plotlist = lapply(7:10, function(k) {
  plot(obj.svd, type = "scores", scores = 2 * k - 1:0, coeff = 0.6) +
    aes(color = S > 0.9) +  # threshold based on histogram
    scale_colour_viridis_d()
}), scale = 0.95)
ggsave(plot=setB,filename=file.dir %&% 
  "plots/outlier-detection_unrelateds_maf01_pc13-20_threshold-statp9.png", width=8, height=5)
```

Further inspection indeed shows that MOST of the PCs are influenced by outlier samples; esepcially PC1 

# Determine identifiers for outlier individuals

```{r}
keep.vec <- readRDS(file.dir %&% "keep.vec.RDS")
keep.indices <- readRDS(file.dir %&% "keep.indices.RDS")
most.sep <- keep.vec[S > 0.9]
```

```{r}
lab.file <- serv.dir%&%"shared/reference_datasets/mais_information/"%&%
"reference-population-labels.txt"
lab.df <- lab.df <- fread(lab.file,header=TRUE)
```

```{r}
outlier.df <- filter(lab.df,sample%in%most.sep)
```
